version: '3'

services:
  proxy_server:
    container_name: proxy_server
    build: ./app 
    ports:
      - '80:80'
      - '443:443'
    restart: always
    networks:
      - shared
    volumes:
      - ./default/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./default/proxy.conf:/etc/nginx/proxy.conf:rw
      - ./nginx-config:/etc/nginx/conf.d:rw
      - ./certs/letsencrypt:/etc/letsencrypt
#      - ./static_images:/data/images
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
 
networks:
  shared:
    external:
      name: shared
