name: Build and Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

env:
  APP_DIR: /home/ubuntu/docker/student_app
  COMPOSE_FILE: docker-compose.yml
  ASG_SCRIPT_PATH: /home/ubuntu/asg/update_asg.sh

jobs:
  build-and-deploy:
    name: Build and Deploy with Docker Compose + ASG Update
    runs-on: signoz

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop Existing Containers
        working-directory: ${{ env.APP_DIR }}
        run: docker compose -f $COMPOSE_FILE down || true

      - name: Build and Start Containers
        working-directory: ${{ env.APP_DIR }}
        run: docker compose -f $COMPOSE_FILE up -d --build

      - name: Run ASG Update Script
        run: |
          echo "Running ASG update script from: /home/ubuntu/asg/update_asg.sh"
          sudo chmod +x /home/ubuntu/asg/update_asg.sh
          /home/ubuntu/asg/update_asg.sh
